"""
pip3 install tqdm aiohttp
"""
import asyncio
import csv

from aiohttp import ClientSession
from tqdm import tqdm


SAVE_DIR = "/tmp/Music"
DATA_FILE = "purple_downloads.csv"  # file generated by the crawler

data = [
    item for item 
    in list(csv.DictReader(open(DATA_FILE), ["title", "download_url", "free_download"]))
    if item["free_download"] == "True"
]


def save_file(title, content):  # blocking
    # TODO: replace with -> https://github.com/Tinche/aiofiles
    with open(
        f"{SAVE_DIR}/Purple Planet Music - {title}.mp3",
        "wb",
    ) as f:
        f.write(content)


async def fetch(title, url, session):
    async with session.get(url) as response:
        return title, await response.read()


async def run(data):
    async with ClientSession() as session:
        tasks = [
            fetch(item["title"], item["download_url"], session)
            for item in data
        ]
        for f in tqdm(asyncio.as_completed(tasks), total=len(tasks)):
            result = await f
            save_file(*result)


loop = asyncio.get_event_loop()
future = asyncio.ensure_future(run(data))
loop.run_until_complete(future)
